### ISSUE TITLE
Need a release manage

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/each#6]
We need a release manager, who uploads our release to Maven central repository, and update Github pages.

**Comment by mengmeng0927** [comment]
Is that anyone of us can release to Maven?

**Comment by Atry** [comment]
Leave a comment at https://issues.sonatype.org/browse/OSSRH-15918 if you need the permission to release

**Comment by Atry** [comment]
But we still need to decide the project name first ...
